platform :ios, '14.0'
workspace 'Omega'

project 'Omega/Omega.xcodeproj'

def shared_pods
  pod 'ZipArchive'
  pod 'TTTAttributedLabel'
  pod 'TransitionKit'
  pod 'BFNavigationBarDrawer'
  pod 'RNCryptor-objc', '~> 3.0'
  pod 'FlatUIKit'
  pod 'iOS7Colors'
  pod 'PureLayout'
  pod 'IPDashedLineView'
  pod 'MBProgressHUD'
  pod 'THContactPicker'
  pod 'GZIP', '~> 1.0.3'
  pod 'MRProgress'
  pod 'QBImagePickerController'
  pod 'lottie-ios'
  pod 'TOCropViewController'
  pod 'Amplitude'
  pod 'Firebase/Crashlytics'
  pod 'GoogleWebRTC', '~> 1.1'
end

target 'EquipAppBR' do
  shared_pods
end

target 'Mototalk' do
  shared_pods
end

target 'EquipAppBRAppStore' do
  shared_pods
end

target 'MototalkAppStore' do
  shared_pods
end

def shared_pods_extension
  pod 'PureLayout'
  pod 'iOS7Colors'
  pod 'Firebase/Crashlytics'
end

target 'MototalkShareExtension' do
  shared_pods_extension
end

target 'MototalkAppStoreShareExtension' do
  shared_pods_extension
end

target 'EquipAppBRShareExtension' do
  shared_pods_extension
end

target 'EquipAppBRAppStoreShareExtension' do
  shared_pods_extension
end

target 'MototalkBusinessTests' do
  inherit! :search_paths
  # Pods for testing
  shared_pods
end

target 'MototalkBusinessAppStoreTests' do
  inherit! :search_paths
  # Pods for testing
  shared_pods
end

target 'EquipAppBRTests' do
  inherit! :search_paths
  # Pods for testing
  shared_pods
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
    config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
    config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  end
  # NOTE: If you are using a CocoaPods version prior to 0.38, replace `pods_project` with `project` on the below line
  installer.pods_project.targets.each do |target|
    if target.name.end_with? "PureLayout"
      target.build_configurations.each do |build_configuration|
        if build_configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] == 'YES'
          build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'PURELAYOUT_APP_EXTENSIONS=1']
        end
      end
    end
  end
end
