/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vuln.project.sample;
import java.net.URI;
import java.net.URL;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.io.SAXReader;

public class App {
    public static void main(String[] args) throws Exception {
        URL url = new URI(args[0]).toURL();
        System.out.println(parse(url));
    }

    public static Document parse(URL url) throws DocumentException {
        SAXReader reader = new SAXReader(); // CVE-2020-10683
        Document document = reader.read(url);

        return document;
    }
}
